site_name: Latte Luau Style-Guide
site_url: https://luau.latte.to/
repo_name: latte-soft/luau-style-guide
repo_url: https://github.com/latte-soft/luau-style-guide

copyright: Copyright &copy; 2022 Latte Softworks

theme:
  name: material

  favicon: assets/images/latte-logo.png
  #logo: assets/images/latte-logo.svg

  icon:
    logo: material/language-lua
    repo: fontawesome/brands/github

  font:
    text: Inter
    code: JetBrains Mono

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to Light Mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to Dark Mode

  features:
    - navigation.expand
    - navigation.indexes
    - content.code.annotate

nav:
  - Introduction: index.md
  - Fundamental Principles: fundamental-principles.md
  - Style-Guide: style-guide.md

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://latte.to/invite

    - icon: fontawesome/brands/twitter
      link: https://twitter.com/LatteSoftworks

    - icon: fontawesome/brands/github
      link: https://github.com/latte-soft

plugins:
  - search:
      lang:
        - en

markdown_extensions:
  - meta
  - admonition
  - attr_list
  - md_in_html

  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
